# Generated by Django 5.2.5 on 2025-09-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=100)),
                ('paper_title', models.CharField(max_length=255)),
                ('author_keywords', models.TextField()),
                ('abstract', models.TextField()),
                ('area', models.CharField(max_length=255)),
            ],
        ),
    ]
