# Generated by Django 5.2.5 on 2025-09-04 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='paper_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
